name: Multo GHC Build
on: [push]
jobs:
  build:
      runs-on: ubuntu-16.04
      strategy:
        matrix:
          ghc: [ '8.2.2', '8.6.5' ]
          cabal: [ '2.0', '3.0' ]
      name: Haskell GHC ${{ matrix.ghc }} sample
      steps:
        - uses: actions/checkout@master
        - name: Setup Haskell
          uses: actions/setup-haskell@v1
          with:
            ghc-version: ${{ matrix.ghc }}
            cabal-version: ${{ matrix.cabal }}
        - run: cabal v2-build
