name: Multi GHC Build
on: [push]
jobs:
  build:
    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macOS-latest]
        os: [ ubuntu-latest, macOS-latest]
        ghc: [ '8.4.4', '8.6.5' ]
        cabal: [ '2.4' ]

    steps:
      - uses: actions/checkout@master
      - uses: haskell-works/setup-haskell@macos-ghcup
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}

      - run: jq --version

      - name: Cabal check
        run: cabal check

      - name: Install dependencies
        run: |
          cabal v2-update

      - name: Build
        run: |
          cabal v2-build

      - name: Test
        run: |
          cabal v2-test
